Improve authorization usability for new users
Zohair-coder/drexel-scraper pull request #106
Opened 2024-07-01 10:24 UTC by sylvieed

Closes #100

2024-07-01 10:26 UTC, sylvieed commented
Will fix tests after work today

2024-07-01 11:57 UTC, Zohair-coder requested changes
Nice work Sylvie! Your PR seems well thought out, good work! I just requested some small changes but overall this seems good.

As for the pipeline failing, it seems like `mypy` is complaining about types. If you need help with fixing it or just want me to fix it for you, let me know.

2024-07-01 11:57 UTC, Zohair-coder commented on README.md
> +You will authenticate the scraper manually as if you were logging into Drexel One, using a one-time code either from an authenticator app or that is texted to you. After setting your Drexel username
Can we change
```
After setting your Drexel username and password, run the scraper as explained above, ...
```
to
```
After setting the `DREXEL_USERNAME` and `DREXEL_PASSWORD` environment variables, run the scraper as explained [above](#Usage), ...
```

It might seem like a nit but it's very easy for newcomers to get confused, so it might be worth changing the wording and adding the link to the Usage section.

2024-07-01 11:57 UTC, Zohair-coder commented on README.md
> +First, [set up authentication](#Authentication).
+1 for creating a separate Authentication section and linking to it.

2024-07-01 11:57 UTC, Zohair-coder commented on README.md
> +To provide your Drexel credentials, set the environment variable `DREXEL_USERNAME` to your Drexel username (abc123) and `DREXEL_PASSWORD` to the password you use to login to Drexel One. You can follo
+1 for adding links to guides for setting environment variables. Our main contributors are going to be Drexel students who might be in their first or second year, so including guides like these is always helpful for them (even if it might be excessive in a **real** project).

2024-07-01 11:57 UTC, Zohair-coder commented on src/config.py
> +
I like this function, but it seems like `config.py` is getting polluted. It was originally intended for end users to change a few variables if necessary. I was considering moving some of the things users might actually be expected to change in a JSON file in the root directory, which this file can then read from. However, I decided against doing so since we can't add comments to JSON files and therefore it'll be difficult for users to figure out what the configuration is for. I'm still not sure how to fix this, and I think the solution is outside of the scope for this PR so don't worry about it, but let me know if you have any ideas.

2024-07-01 11:57 UTC, Zohair-coder commented on src/config.py
> +# This is not required if the user is using a separate authenticator app and will manually approve the login attempt
Good comment.

2024-07-01 21:47 UTC, sylvieed commented on README.md
> +You will authenticate the scraper manually as if you were logging into Drexel One, using a one-time code either from an authenticator app or that is texted to you. After setting your Drexel username
Yep, changed this

2024-07-01 21:49 UTC, sylvieed commented on src/config.py
> +
Yeah, I agree. Have you considered using a yaml file for the configuration? They work similarly to JSON files for configs but can have comments in them. That could then be loaded in in `config.py` along with any environment variables.

2024-07-02 08:37 UTC, Zohair-coder commented on src/config.py
> +
Hmm good idea. I'm familiar with YAML files (I've actually used them [in this project](https://github.com/Zohair-coder/drexel-scraper/blob/main/k8s/drexel-scraper/templates/cronjob.yaml) for deploying the app to Kubernetes). I'm also considering using [TOML](https://toml.io/en/) files for configuration. They allow comments as well. I have a slight bias against YAML because it's pretty strict about indentation and it's often times hard to understand in more deeply nested YAML objects. I'll look into the differences further and test them out. Thanks!

2024-07-02 08:39 UTC, Zohair-coder approved these changes

2024-07-02 08:41 UTC, merged